import { MenuItem } from "@/types";
import { ExtraGroupData } from "@/components/restaurant/product-extras-group";

export const mockRestaurant = {
    id: "1",
    name: "Pizza Delícia",
    description: "As melhores pizzas da região com ingredientes frescos",
    category: "Pizza",
    cover_image: "/restaurants/pizza-cover.jpg",
    logo_image: "/restaurants/pizza-logo.jpg",
    rating: 4.8,
    total_reviews: 234,
    delivery_time: 30,
    delivery_fee: 5.99,
    min_order_value: 20,
    latitude: -23.5505,
    longitude: -46.6333,
    address: "Rua das Pizzas, 123 - Centro",
    phone: "(11) 98765-4321",
    is_open: true,
    opening_hours: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
};

export const mockMenuItems: MenuItem[] = [
    {
        id: "1",
        restaurant_id: "1",
        category_id: "pizzas",
        name: "Pizza Margherita",
        description: "Molho de tomate, mussarela, manjericão fresco",
        price: 45.90,
        image_url: "/menu/margherita.jpg",
        is_available: true,
        preparation_time: 25,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "2",
        restaurant_id: "1",
        category_id: "pizzas",
        name: "Pizza Calabresa",
        description: "Calabresa, cebola, azeitonas, mussarela",
        price: 48.90,
        image_url: "/menu/calabresa.jpg",
        is_available: true,
        preparation_time: 25,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "3",
        restaurant_id: "1",
        category_id: "pizzas",
        name: "Pizza Quatro Queijos",
        description: "Mussarela, provolone, gorgonzola, parmesão",
        price: 52.90,
        image_url: "/menu/quatro-queijos.jpg",
        is_available: true,
        preparation_time: 25,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "4",
        restaurant_id: "1",
        category_id: "drinks",
        name: "Coca-Cola 2L",
        description: "Refrigerante Coca-Cola 2 litros gelado",
        price: 12.00,
        image_url: "/menu/coca-cola.jpg",
        is_available: true,
        preparation_time: 5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "5",
        restaurant_id: "1",
        category_id: "desserts",
        name: "Pudim de Leite",
        description: "Pudim caseiro cremoso com calda de caramelo",
        price: 15.90,
        image_url: "/menu/pudim.jpg",
        is_available: true,
        preparation_time: 10,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

export const mockExtraGroups: ExtraGroupData[] = [
    {
        id: "crust",
        name: "Tipo de Borda",
        required: false,
        minSelection: 0,
        maxSelection: 1,
        extras: [
            { id: "crust-1", name: "Borda Catupiry", price: 8.00 },
            { id: "crust-2", name: "Borda Cheddar", price: 7.00 },
            { id: "crust-3", name: "Borda Chocolate", price: 6.00 },
        ],
    },
    {
        id: "extras",
        name: "Adicionais",
        required: false,
        minSelection: 0,
        maxSelection: 3,
        extras: [
            { id: "extra-1", name: "Bacon", price: 5.00 },
            { id: "extra-2", name: "Azeitona", price: 3.00 },
            { id: "extra-3", name: "Orégano Extra", price: 1.00 },
            { id: "extra-4", name: "Parmesão Ralado", price: 2.00 },
        ],
    },
];
